# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c780e47b0e7a5e1d29a37471c5ed9c1265586ba58611ff92c57130fb9bd60fb65d373c7bd957369d862ce2c5b9d9a9fd2a9717e2e334e6f4b7b504697651e400

test:
  secret_key_base: 12cd919f462ef39e9c4b44c658e051a93eef02c89dbaa00b6e112b4ac1b4473f9ad6690a0a7bdbc2e0a25d67b8f36066e22b5bff5564b639f5e53ae41e347ca1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
